version: '3.8'

services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
   
    volumes:
      - mongo-data:/data/db
   



volumes:
  mongo-data: